### ISSUE TITLE
Add a flag for SCSS

### ISSUE THREAD

**Issue by mattxwang** [stylelint/create-stylelint#17]
### What is the problem you're trying to solve?

Currently, the tool assumes a standard vanilla CSS setup. This may not work for projects that use SCSS (among other preprocessors, etc.).

### What solution would you like to see?

In https://github.com/stylelint/stylelint/issues/4269#issuecomment-1016412442, @jeddy mentioned:

> Then we can add a flag for SCSS, e.g. 
> 
> ```
> npm init stylelint -- --template scss
> ```

This seems like a good idea to me, though also happy to workshop what it'd be named, etc. 

In addition, are there other templates that we should consider?

Happy to contribute this feature as well!

**Comment by jeddy3** [comment]
Having thought about it some more, we're opening a can of worms if we include community configs in tool. We can't guarantee they'll be in sync with Stylelint, and it's a neverending churn.

It's better if we draw a clear line:

- writing vanilla CSS? Then use Stylelint's init, official config and built-in rules
- writing something else? Then you'll need to manually setup Stylelint using our guide

I plan to open a PR before the `15.3.0` release to update our [Getting started guide](https://stylelint.io/user-guide/get-started) to reflect this.

**Comment by mattxwang** [comment]
Totally understand! In that case, shall we close this issue?
