### ISSUE TITLE
Release 0.3.0

### ISSUE THREAD

**Issue by mattxwang** [stylelint/create-stylelint#19]
In https://github.com/stylelint/stylelint/issues/6743#issuecomment-1489843436:

> It might be good timing to publish also `create-stylelint`: https://github.com/stylelint/create-stylelint/compare/0.2.0...main

I agree! Happy to do the release process for this one if we'd like. It seems like the workflow is:

1. update changelog
2. update `package.json`
3. push to npm

If we think this is a good idea, I can open a "Prepare 0.3.0" PR (or commit) that does the first two items.

**Comment by ybiquitous** [comment]
> I can open a "Prepare 0.3.0" PR (or commit) that does the first two items.

Agree. Let's open PR and release it!
